name: demo1 for MAA

on:
  workflow_dispatch:
  push:
    paths:
      - "action.yml"
      - "python/**"
      - ".github/workflows/demo1-MAA.yml

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x64]
    steps:
      - name: Upload MAA win
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: 'MAA-*-win-${{ matrix.arch }}.zip'
          mirrorchyan_rid: demo1

          github_token: ${{ secrets.GITHUB_TOKEN }}

          owner: MaaAssistantArknights
          repo: MaaAssistantArknights
          upload_token: ${{ secrets.MirrorChyanUploadTokenForDemo1 }}
          os: win
          arch: ${{ matrix.arch }}

      - name: Upload MAA macos
        uses: MirrorChyan/uploading-action@v1
        if: always()
        with:
          filetype: latest-release
          filename: "MAA-*-macos-universal.dmg"
          extra_zip: true
          mirrorchyan_rid: demo1

          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          upload_token: ${{ secrets.MirrorChyanUploadTokenForDemo1 }}
          os: macos
          arch: ${{ matrix.arch }}
