name: demo1-MAA

on:
  workflow_dispatch:
  push:
    paths:
      - "action.yml"
      - "python/**"
      - ".github/workflows/demo1.yml"

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [win]
        arch: [arm64, x64]
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "*MAA-*-${{ matrix.os }}-${{ matrix.arch }}.zip"
          mirrorchyan_rid: demo1

          github_token: ${{ secrets.GITHUB_TOKEN }}

          owner: MaaAssistantArknights
          repo: MaaAssistantArknights
          upload_token: ${{ secrets.MirrorChyanUploadTokenForDemo1 }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
